### ISSUE TITLE
Care: case sensitivity may be present for unique id

### ISSUE THREAD

**Issue by rhubarbselleven** [Vulnetix/vulnetix#46]
https://github.com/Vulnetix/vulnetix/blob/c44381a6e975c980dfd790c7bcb99ff4d6527902/prisma/schema.prisma#L25

* https://www.prisma.io/docs/orm/prisma-client/queries/case-sensitivity
* https://www.prisma.io/docs/orm/reference/prisma-schema-reference#id

There's nothing to suggest case sensitivity is or is not in play for the `@unique @id` and relies on the collation for the database.

As a potentially sanitised but user supplied field, the following could both be `@unique`

* <pope@vatican.com>
* <Pope@vatican.com>

Not a bug, but a note of caution.

**Comment by 0x73746F66** [comment]
thank you for the issue
